<?php
/**
 * RunsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Qase\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Qase.io API
 *
 * Qase API Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Qase\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Qase\Client\ApiException;
use Qase\Client\Configuration;
use Qase\Client\HeaderSelector;
use Qase\Client\ObjectSerializer;

/**
 * RunsApi Class Doc Comment
 *
 * @category Class
 * @package  Qase\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RunsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'completeRun' => [
            'application/json',
        ],
        'createRun' => [
            'application/json',
        ],
        'deleteRun' => [
            'application/json',
        ],
        'getRun' => [
            'application/json',
        ],
        'getRuns' => [
            'application/json',
        ],
        'updateRunPublicity' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation completeRun
     *
     * Complete a specific run.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  int $id Identifier. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['completeRun'] to see the possible values for this operation
     *
     * @throws \Qase\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Qase\Client\Model\Response
     */
    public function completeRun($code, $id, string $contentType = self::contentTypes['completeRun'][0])
    {
        list($response) = $this->completeRunWithHttpInfo($code, $id, $contentType);
        return $response;
    }

    /**
     * Operation completeRunWithHttpInfo
     *
     * Complete a specific run.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  int $id Identifier. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['completeRun'] to see the possible values for this operation
     *
     * @throws \Qase\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Qase\Client\Model\Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function completeRunWithHttpInfo($code, $id, string $contentType = self::contentTypes['completeRun'][0])
    {
        $request = $this->completeRunRequest($code, $id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Qase\Client\Model\Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Qase\Client\Model\Response' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Qase\Client\Model\Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Qase\Client\Model\Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Qase\Client\Model\Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation completeRunAsync
     *
     * Complete a specific run.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  int $id Identifier. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['completeRun'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function completeRunAsync($code, $id, string $contentType = self::contentTypes['completeRun'][0])
    {
        return $this->completeRunAsyncWithHttpInfo($code, $id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation completeRunAsyncWithHttpInfo
     *
     * Complete a specific run.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  int $id Identifier. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['completeRun'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function completeRunAsyncWithHttpInfo($code, $id, string $contentType = self::contentTypes['completeRun'][0])
    {
        $returnType = '\Qase\Client\Model\Response';
        $request = $this->completeRunRequest($code, $id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'completeRun'
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  int $id Identifier. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['completeRun'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function completeRunRequest($code, $id, string $contentType = self::contentTypes['completeRun'][0])
    {

        // verify the required parameter 'code' is set
        if ($code === null || (is_array($code) && count($code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $code when calling completeRun'
            );
        }
        if (strlen($code) > 10) {
            throw new \InvalidArgumentException('invalid length for "$code" when calling RunsApi.completeRun, must be smaller than or equal to 10.');
        }
        if (strlen($code) < 2) {
            throw new \InvalidArgumentException('invalid length for "$code" when calling RunsApi.completeRun, must be bigger than or equal to 2.');
        }
        
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling completeRun'
            );
        }


        $resourcePath = '/run/{code}/{id}/complete';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($code !== null) {
            $resourcePath = str_replace(
                '{' . 'code' . '}',
                ObjectSerializer::toPathValue($code),
                $resourcePath
            );
        }
        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation createRun
     *
     * Create a new run.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  \Qase\Client\Model\RunCreate $runCreate runCreate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createRun'] to see the possible values for this operation
     *
     * @throws \Qase\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Qase\Client\Model\IdResponse
     */
    public function createRun($code, $runCreate, string $contentType = self::contentTypes['createRun'][0])
    {
        list($response) = $this->createRunWithHttpInfo($code, $runCreate, $contentType);
        return $response;
    }

    /**
     * Operation createRunWithHttpInfo
     *
     * Create a new run.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  \Qase\Client\Model\RunCreate $runCreate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createRun'] to see the possible values for this operation
     *
     * @throws \Qase\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Qase\Client\Model\IdResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function createRunWithHttpInfo($code, $runCreate, string $contentType = self::contentTypes['createRun'][0])
    {
        $request = $this->createRunRequest($code, $runCreate, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Qase\Client\Model\IdResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Qase\Client\Model\IdResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Qase\Client\Model\IdResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Qase\Client\Model\IdResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Qase\Client\Model\IdResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createRunAsync
     *
     * Create a new run.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  \Qase\Client\Model\RunCreate $runCreate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createRun'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createRunAsync($code, $runCreate, string $contentType = self::contentTypes['createRun'][0])
    {
        return $this->createRunAsyncWithHttpInfo($code, $runCreate, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createRunAsyncWithHttpInfo
     *
     * Create a new run.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  \Qase\Client\Model\RunCreate $runCreate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createRun'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createRunAsyncWithHttpInfo($code, $runCreate, string $contentType = self::contentTypes['createRun'][0])
    {
        $returnType = '\Qase\Client\Model\IdResponse';
        $request = $this->createRunRequest($code, $runCreate, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createRun'
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  \Qase\Client\Model\RunCreate $runCreate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createRun'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createRunRequest($code, $runCreate, string $contentType = self::contentTypes['createRun'][0])
    {

        // verify the required parameter 'code' is set
        if ($code === null || (is_array($code) && count($code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $code when calling createRun'
            );
        }
        if (strlen($code) > 10) {
            throw new \InvalidArgumentException('invalid length for "$code" when calling RunsApi.createRun, must be smaller than or equal to 10.');
        }
        if (strlen($code) < 2) {
            throw new \InvalidArgumentException('invalid length for "$code" when calling RunsApi.createRun, must be bigger than or equal to 2.');
        }
        
        // verify the required parameter 'runCreate' is set
        if ($runCreate === null || (is_array($runCreate) && count($runCreate) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $runCreate when calling createRun'
            );
        }


        $resourcePath = '/run/{code}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($code !== null) {
            $resourcePath = str_replace(
                '{' . 'code' . '}',
                ObjectSerializer::toPathValue($code),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($runCreate)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($runCreate));
            } else {
                $httpBody = $runCreate;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteRun
     *
     * Delete run.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  int $id Identifier. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteRun'] to see the possible values for this operation
     *
     * @throws \Qase\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Qase\Client\Model\IdResponse
     */
    public function deleteRun($code, $id, string $contentType = self::contentTypes['deleteRun'][0])
    {
        list($response) = $this->deleteRunWithHttpInfo($code, $id, $contentType);
        return $response;
    }

    /**
     * Operation deleteRunWithHttpInfo
     *
     * Delete run.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  int $id Identifier. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteRun'] to see the possible values for this operation
     *
     * @throws \Qase\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Qase\Client\Model\IdResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteRunWithHttpInfo($code, $id, string $contentType = self::contentTypes['deleteRun'][0])
    {
        $request = $this->deleteRunRequest($code, $id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Qase\Client\Model\IdResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Qase\Client\Model\IdResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Qase\Client\Model\IdResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Qase\Client\Model\IdResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Qase\Client\Model\IdResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation deleteRunAsync
     *
     * Delete run.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  int $id Identifier. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteRun'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteRunAsync($code, $id, string $contentType = self::contentTypes['deleteRun'][0])
    {
        return $this->deleteRunAsyncWithHttpInfo($code, $id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteRunAsyncWithHttpInfo
     *
     * Delete run.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  int $id Identifier. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteRun'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteRunAsyncWithHttpInfo($code, $id, string $contentType = self::contentTypes['deleteRun'][0])
    {
        $returnType = '\Qase\Client\Model\IdResponse';
        $request = $this->deleteRunRequest($code, $id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteRun'
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  int $id Identifier. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteRun'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteRunRequest($code, $id, string $contentType = self::contentTypes['deleteRun'][0])
    {

        // verify the required parameter 'code' is set
        if ($code === null || (is_array($code) && count($code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $code when calling deleteRun'
            );
        }
        if (strlen($code) > 10) {
            throw new \InvalidArgumentException('invalid length for "$code" when calling RunsApi.deleteRun, must be smaller than or equal to 10.');
        }
        if (strlen($code) < 2) {
            throw new \InvalidArgumentException('invalid length for "$code" when calling RunsApi.deleteRun, must be bigger than or equal to 2.');
        }
        
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling deleteRun'
            );
        }


        $resourcePath = '/run/{code}/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($code !== null) {
            $resourcePath = str_replace(
                '{' . 'code' . '}',
                ObjectSerializer::toPathValue($code),
                $resourcePath
            );
        }
        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getRun
     *
     * Get a specific run.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  int $id Identifier. (required)
     * @param  string $include Include a list of related entities IDs into response. Should be separated by comma. Possible values: cases, defects (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRun'] to see the possible values for this operation
     *
     * @throws \Qase\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Qase\Client\Model\RunResponse
     */
    public function getRun($code, $id, $include = null, string $contentType = self::contentTypes['getRun'][0])
    {
        list($response) = $this->getRunWithHttpInfo($code, $id, $include, $contentType);
        return $response;
    }

    /**
     * Operation getRunWithHttpInfo
     *
     * Get a specific run.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  int $id Identifier. (required)
     * @param  string $include Include a list of related entities IDs into response. Should be separated by comma. Possible values: cases, defects (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRun'] to see the possible values for this operation
     *
     * @throws \Qase\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Qase\Client\Model\RunResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getRunWithHttpInfo($code, $id, $include = null, string $contentType = self::contentTypes['getRun'][0])
    {
        $request = $this->getRunRequest($code, $id, $include, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Qase\Client\Model\RunResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Qase\Client\Model\RunResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Qase\Client\Model\RunResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Qase\Client\Model\RunResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Qase\Client\Model\RunResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getRunAsync
     *
     * Get a specific run.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  int $id Identifier. (required)
     * @param  string $include Include a list of related entities IDs into response. Should be separated by comma. Possible values: cases, defects (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRun'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getRunAsync($code, $id, $include = null, string $contentType = self::contentTypes['getRun'][0])
    {
        return $this->getRunAsyncWithHttpInfo($code, $id, $include, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getRunAsyncWithHttpInfo
     *
     * Get a specific run.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  int $id Identifier. (required)
     * @param  string $include Include a list of related entities IDs into response. Should be separated by comma. Possible values: cases, defects (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRun'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getRunAsyncWithHttpInfo($code, $id, $include = null, string $contentType = self::contentTypes['getRun'][0])
    {
        $returnType = '\Qase\Client\Model\RunResponse';
        $request = $this->getRunRequest($code, $id, $include, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getRun'
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  int $id Identifier. (required)
     * @param  string $include Include a list of related entities IDs into response. Should be separated by comma. Possible values: cases, defects (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRun'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getRunRequest($code, $id, $include = null, string $contentType = self::contentTypes['getRun'][0])
    {

        // verify the required parameter 'code' is set
        if ($code === null || (is_array($code) && count($code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $code when calling getRun'
            );
        }
        if (strlen($code) > 10) {
            throw new \InvalidArgumentException('invalid length for "$code" when calling RunsApi.getRun, must be smaller than or equal to 10.');
        }
        if (strlen($code) < 2) {
            throw new \InvalidArgumentException('invalid length for "$code" when calling RunsApi.getRun, must be bigger than or equal to 2.');
        }
        
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getRun'
            );
        }



        $resourcePath = '/run/{code}/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $include,
            'include', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($code !== null) {
            $resourcePath = str_replace(
                '{' . 'code' . '}',
                ObjectSerializer::toPathValue($code),
                $resourcePath
            );
        }
        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getRuns
     *
     * Get all runs.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  string $search search (optional)
     * @param  string $status A list of status values separated by comma. Possible values: active, complete, abort. (optional)
     * @param  int $milestone milestone (optional)
     * @param  int $environment environment (optional)
     * @param  int $fromStartTime fromStartTime (optional)
     * @param  int $toStartTime toStartTime (optional)
     * @param  int $limit A number of entities in result set. (optional, default to 10)
     * @param  int $offset How many entities should be skipped. (optional, default to 0)
     * @param  string $include Include a list of related entities IDs into response. Should be separated by comma. Possible values: cases, defects (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRuns'] to see the possible values for this operation
     *
     * @throws \Qase\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Qase\Client\Model\RunListResponse
     */
    public function getRuns($code, $search = null, $status = null, $milestone = null, $environment = null, $fromStartTime = null, $toStartTime = null, $limit = 10, $offset = 0, $include = null, string $contentType = self::contentTypes['getRuns'][0])
    {
        list($response) = $this->getRunsWithHttpInfo($code, $search, $status, $milestone, $environment, $fromStartTime, $toStartTime, $limit, $offset, $include, $contentType);
        return $response;
    }

    /**
     * Operation getRunsWithHttpInfo
     *
     * Get all runs.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  string $search (optional)
     * @param  string $status A list of status values separated by comma. Possible values: active, complete, abort. (optional)
     * @param  int $milestone (optional)
     * @param  int $environment (optional)
     * @param  int $fromStartTime (optional)
     * @param  int $toStartTime (optional)
     * @param  int $limit A number of entities in result set. (optional, default to 10)
     * @param  int $offset How many entities should be skipped. (optional, default to 0)
     * @param  string $include Include a list of related entities IDs into response. Should be separated by comma. Possible values: cases, defects (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRuns'] to see the possible values for this operation
     *
     * @throws \Qase\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Qase\Client\Model\RunListResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getRunsWithHttpInfo($code, $search = null, $status = null, $milestone = null, $environment = null, $fromStartTime = null, $toStartTime = null, $limit = 10, $offset = 0, $include = null, string $contentType = self::contentTypes['getRuns'][0])
    {
        $request = $this->getRunsRequest($code, $search, $status, $milestone, $environment, $fromStartTime, $toStartTime, $limit, $offset, $include, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Qase\Client\Model\RunListResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Qase\Client\Model\RunListResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Qase\Client\Model\RunListResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Qase\Client\Model\RunListResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Qase\Client\Model\RunListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getRunsAsync
     *
     * Get all runs.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  string $search (optional)
     * @param  string $status A list of status values separated by comma. Possible values: active, complete, abort. (optional)
     * @param  int $milestone (optional)
     * @param  int $environment (optional)
     * @param  int $fromStartTime (optional)
     * @param  int $toStartTime (optional)
     * @param  int $limit A number of entities in result set. (optional, default to 10)
     * @param  int $offset How many entities should be skipped. (optional, default to 0)
     * @param  string $include Include a list of related entities IDs into response. Should be separated by comma. Possible values: cases, defects (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRuns'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getRunsAsync($code, $search = null, $status = null, $milestone = null, $environment = null, $fromStartTime = null, $toStartTime = null, $limit = 10, $offset = 0, $include = null, string $contentType = self::contentTypes['getRuns'][0])
    {
        return $this->getRunsAsyncWithHttpInfo($code, $search, $status, $milestone, $environment, $fromStartTime, $toStartTime, $limit, $offset, $include, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getRunsAsyncWithHttpInfo
     *
     * Get all runs.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  string $search (optional)
     * @param  string $status A list of status values separated by comma. Possible values: active, complete, abort. (optional)
     * @param  int $milestone (optional)
     * @param  int $environment (optional)
     * @param  int $fromStartTime (optional)
     * @param  int $toStartTime (optional)
     * @param  int $limit A number of entities in result set. (optional, default to 10)
     * @param  int $offset How many entities should be skipped. (optional, default to 0)
     * @param  string $include Include a list of related entities IDs into response. Should be separated by comma. Possible values: cases, defects (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRuns'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getRunsAsyncWithHttpInfo($code, $search = null, $status = null, $milestone = null, $environment = null, $fromStartTime = null, $toStartTime = null, $limit = 10, $offset = 0, $include = null, string $contentType = self::contentTypes['getRuns'][0])
    {
        $returnType = '\Qase\Client\Model\RunListResponse';
        $request = $this->getRunsRequest($code, $search, $status, $milestone, $environment, $fromStartTime, $toStartTime, $limit, $offset, $include, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getRuns'
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  string $search (optional)
     * @param  string $status A list of status values separated by comma. Possible values: active, complete, abort. (optional)
     * @param  int $milestone (optional)
     * @param  int $environment (optional)
     * @param  int $fromStartTime (optional)
     * @param  int $toStartTime (optional)
     * @param  int $limit A number of entities in result set. (optional, default to 10)
     * @param  int $offset How many entities should be skipped. (optional, default to 0)
     * @param  string $include Include a list of related entities IDs into response. Should be separated by comma. Possible values: cases, defects (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRuns'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getRunsRequest($code, $search = null, $status = null, $milestone = null, $environment = null, $fromStartTime = null, $toStartTime = null, $limit = 10, $offset = 0, $include = null, string $contentType = self::contentTypes['getRuns'][0])
    {

        // verify the required parameter 'code' is set
        if ($code === null || (is_array($code) && count($code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $code when calling getRuns'
            );
        }
        if (strlen($code) > 10) {
            throw new \InvalidArgumentException('invalid length for "$code" when calling RunsApi.getRuns, must be smaller than or equal to 10.');
        }
        if (strlen($code) < 2) {
            throw new \InvalidArgumentException('invalid length for "$code" when calling RunsApi.getRuns, must be bigger than or equal to 2.');
        }
        






        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling RunsApi.getRuns, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling RunsApi.getRuns, must be bigger than or equal to 1.');
        }
        
        if ($offset !== null && $offset > 100000) {
            throw new \InvalidArgumentException('invalid value for "$offset" when calling RunsApi.getRuns, must be smaller than or equal to 100000.');
        }
        if ($offset !== null && $offset < 0) {
            throw new \InvalidArgumentException('invalid value for "$offset" when calling RunsApi.getRuns, must be bigger than or equal to 0.');
        }
        


        $resourcePath = '/run/{code}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $search,
            'search', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $status,
            'status', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $milestone,
            'milestone', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $environment,
            'environment', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fromStartTime,
            'from_start_time', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $toStartTime,
            'to_start_time', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $offset,
            'offset', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $include,
            'include', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($code !== null) {
            $resourcePath = str_replace(
                '{' . 'code' . '}',
                ObjectSerializer::toPathValue($code),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateRunPublicity
     *
     * Update publicity of a specific run.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  int $id Identifier. (required)
     * @param  \Qase\Client\Model\RunPublic $runPublic runPublic (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateRunPublicity'] to see the possible values for this operation
     *
     * @throws \Qase\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Qase\Client\Model\RunPublicResponse
     */
    public function updateRunPublicity($code, $id, $runPublic, string $contentType = self::contentTypes['updateRunPublicity'][0])
    {
        list($response) = $this->updateRunPublicityWithHttpInfo($code, $id, $runPublic, $contentType);
        return $response;
    }

    /**
     * Operation updateRunPublicityWithHttpInfo
     *
     * Update publicity of a specific run.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  int $id Identifier. (required)
     * @param  \Qase\Client\Model\RunPublic $runPublic (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateRunPublicity'] to see the possible values for this operation
     *
     * @throws \Qase\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Qase\Client\Model\RunPublicResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateRunPublicityWithHttpInfo($code, $id, $runPublic, string $contentType = self::contentTypes['updateRunPublicity'][0])
    {
        $request = $this->updateRunPublicityRequest($code, $id, $runPublic, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Qase\Client\Model\RunPublicResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Qase\Client\Model\RunPublicResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Qase\Client\Model\RunPublicResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Qase\Client\Model\RunPublicResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Qase\Client\Model\RunPublicResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateRunPublicityAsync
     *
     * Update publicity of a specific run.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  int $id Identifier. (required)
     * @param  \Qase\Client\Model\RunPublic $runPublic (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateRunPublicity'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateRunPublicityAsync($code, $id, $runPublic, string $contentType = self::contentTypes['updateRunPublicity'][0])
    {
        return $this->updateRunPublicityAsyncWithHttpInfo($code, $id, $runPublic, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateRunPublicityAsyncWithHttpInfo
     *
     * Update publicity of a specific run.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  int $id Identifier. (required)
     * @param  \Qase\Client\Model\RunPublic $runPublic (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateRunPublicity'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateRunPublicityAsyncWithHttpInfo($code, $id, $runPublic, string $contentType = self::contentTypes['updateRunPublicity'][0])
    {
        $returnType = '\Qase\Client\Model\RunPublicResponse';
        $request = $this->updateRunPublicityRequest($code, $id, $runPublic, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateRunPublicity'
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  int $id Identifier. (required)
     * @param  \Qase\Client\Model\RunPublic $runPublic (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateRunPublicity'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateRunPublicityRequest($code, $id, $runPublic, string $contentType = self::contentTypes['updateRunPublicity'][0])
    {

        // verify the required parameter 'code' is set
        if ($code === null || (is_array($code) && count($code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $code when calling updateRunPublicity'
            );
        }
        if (strlen($code) > 10) {
            throw new \InvalidArgumentException('invalid length for "$code" when calling RunsApi.updateRunPublicity, must be smaller than or equal to 10.');
        }
        if (strlen($code) < 2) {
            throw new \InvalidArgumentException('invalid length for "$code" when calling RunsApi.updateRunPublicity, must be bigger than or equal to 2.');
        }
        
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling updateRunPublicity'
            );
        }

        // verify the required parameter 'runPublic' is set
        if ($runPublic === null || (is_array($runPublic) && count($runPublic) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $runPublic when calling updateRunPublicity'
            );
        }


        $resourcePath = '/run/{code}/{id}/public';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($code !== null) {
            $resourcePath = str_replace(
                '{' . 'code' . '}',
                ObjectSerializer::toPathValue($code),
                $resourcePath
            );
        }
        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($runPublic)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($runPublic));
            } else {
                $httpBody = $runPublic;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
