<?php
/**
 * SharedStepsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Qase\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Qase.io API
 *
 * Qase API Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Qase\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Qase\Client\ApiException;
use Qase\Client\Configuration;
use Qase\Client\HeaderSelector;
use Qase\Client\ObjectSerializer;

/**
 * SharedStepsApi Class Doc Comment
 *
 * @category Class
 * @package  Qase\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SharedStepsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createSharedStep' => [
            'application/json',
        ],
        'deleteSharedStep' => [
            'application/json',
        ],
        'getSharedStep' => [
            'application/json',
        ],
        'getSharedSteps' => [
            'application/json',
        ],
        'updateSharedStep' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createSharedStep
     *
     * Create a new shared step.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  \Qase\Client\Model\SharedStepCreate $sharedStepCreate sharedStepCreate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createSharedStep'] to see the possible values for this operation
     *
     * @throws \Qase\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Qase\Client\Model\HashResponse
     */
    public function createSharedStep($code, $sharedStepCreate, string $contentType = self::contentTypes['createSharedStep'][0])
    {
        list($response) = $this->createSharedStepWithHttpInfo($code, $sharedStepCreate, $contentType);
        return $response;
    }

    /**
     * Operation createSharedStepWithHttpInfo
     *
     * Create a new shared step.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  \Qase\Client\Model\SharedStepCreate $sharedStepCreate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createSharedStep'] to see the possible values for this operation
     *
     * @throws \Qase\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Qase\Client\Model\HashResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function createSharedStepWithHttpInfo($code, $sharedStepCreate, string $contentType = self::contentTypes['createSharedStep'][0])
    {
        $request = $this->createSharedStepRequest($code, $sharedStepCreate, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Qase\Client\Model\HashResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Qase\Client\Model\HashResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Qase\Client\Model\HashResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Qase\Client\Model\HashResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Qase\Client\Model\HashResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createSharedStepAsync
     *
     * Create a new shared step.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  \Qase\Client\Model\SharedStepCreate $sharedStepCreate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createSharedStep'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createSharedStepAsync($code, $sharedStepCreate, string $contentType = self::contentTypes['createSharedStep'][0])
    {
        return $this->createSharedStepAsyncWithHttpInfo($code, $sharedStepCreate, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createSharedStepAsyncWithHttpInfo
     *
     * Create a new shared step.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  \Qase\Client\Model\SharedStepCreate $sharedStepCreate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createSharedStep'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createSharedStepAsyncWithHttpInfo($code, $sharedStepCreate, string $contentType = self::contentTypes['createSharedStep'][0])
    {
        $returnType = '\Qase\Client\Model\HashResponse';
        $request = $this->createSharedStepRequest($code, $sharedStepCreate, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createSharedStep'
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  \Qase\Client\Model\SharedStepCreate $sharedStepCreate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createSharedStep'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createSharedStepRequest($code, $sharedStepCreate, string $contentType = self::contentTypes['createSharedStep'][0])
    {

        // verify the required parameter 'code' is set
        if ($code === null || (is_array($code) && count($code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $code when calling createSharedStep'
            );
        }
        if (strlen($code) > 10) {
            throw new \InvalidArgumentException('invalid length for "$code" when calling SharedStepsApi.createSharedStep, must be smaller than or equal to 10.');
        }
        if (strlen($code) < 2) {
            throw new \InvalidArgumentException('invalid length for "$code" when calling SharedStepsApi.createSharedStep, must be bigger than or equal to 2.');
        }
        
        // verify the required parameter 'sharedStepCreate' is set
        if ($sharedStepCreate === null || (is_array($sharedStepCreate) && count($sharedStepCreate) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sharedStepCreate when calling createSharedStep'
            );
        }


        $resourcePath = '/shared_step/{code}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($code !== null) {
            $resourcePath = str_replace(
                '{' . 'code' . '}',
                ObjectSerializer::toPathValue($code),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($sharedStepCreate)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($sharedStepCreate));
            } else {
                $httpBody = $sharedStepCreate;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteSharedStep
     *
     * Delete shared step.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  string $hash Hash. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteSharedStep'] to see the possible values for this operation
     *
     * @throws \Qase\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Qase\Client\Model\HashResponse
     */
    public function deleteSharedStep($code, $hash, string $contentType = self::contentTypes['deleteSharedStep'][0])
    {
        list($response) = $this->deleteSharedStepWithHttpInfo($code, $hash, $contentType);
        return $response;
    }

    /**
     * Operation deleteSharedStepWithHttpInfo
     *
     * Delete shared step.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  string $hash Hash. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteSharedStep'] to see the possible values for this operation
     *
     * @throws \Qase\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Qase\Client\Model\HashResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteSharedStepWithHttpInfo($code, $hash, string $contentType = self::contentTypes['deleteSharedStep'][0])
    {
        $request = $this->deleteSharedStepRequest($code, $hash, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Qase\Client\Model\HashResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Qase\Client\Model\HashResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Qase\Client\Model\HashResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Qase\Client\Model\HashResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Qase\Client\Model\HashResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation deleteSharedStepAsync
     *
     * Delete shared step.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  string $hash Hash. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteSharedStep'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteSharedStepAsync($code, $hash, string $contentType = self::contentTypes['deleteSharedStep'][0])
    {
        return $this->deleteSharedStepAsyncWithHttpInfo($code, $hash, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteSharedStepAsyncWithHttpInfo
     *
     * Delete shared step.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  string $hash Hash. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteSharedStep'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteSharedStepAsyncWithHttpInfo($code, $hash, string $contentType = self::contentTypes['deleteSharedStep'][0])
    {
        $returnType = '\Qase\Client\Model\HashResponse';
        $request = $this->deleteSharedStepRequest($code, $hash, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteSharedStep'
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  string $hash Hash. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteSharedStep'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteSharedStepRequest($code, $hash, string $contentType = self::contentTypes['deleteSharedStep'][0])
    {

        // verify the required parameter 'code' is set
        if ($code === null || (is_array($code) && count($code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $code when calling deleteSharedStep'
            );
        }
        if (strlen($code) > 10) {
            throw new \InvalidArgumentException('invalid length for "$code" when calling SharedStepsApi.deleteSharedStep, must be smaller than or equal to 10.');
        }
        if (strlen($code) < 2) {
            throw new \InvalidArgumentException('invalid length for "$code" when calling SharedStepsApi.deleteSharedStep, must be bigger than or equal to 2.');
        }
        
        // verify the required parameter 'hash' is set
        if ($hash === null || (is_array($hash) && count($hash) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $hash when calling deleteSharedStep'
            );
        }


        $resourcePath = '/shared_step/{code}/{hash}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($code !== null) {
            $resourcePath = str_replace(
                '{' . 'code' . '}',
                ObjectSerializer::toPathValue($code),
                $resourcePath
            );
        }
        // path params
        if ($hash !== null) {
            $resourcePath = str_replace(
                '{' . 'hash' . '}',
                ObjectSerializer::toPathValue($hash),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getSharedStep
     *
     * Get a specific shared step.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  string $hash Hash. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSharedStep'] to see the possible values for this operation
     *
     * @throws \Qase\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Qase\Client\Model\SharedStepResponse
     */
    public function getSharedStep($code, $hash, string $contentType = self::contentTypes['getSharedStep'][0])
    {
        list($response) = $this->getSharedStepWithHttpInfo($code, $hash, $contentType);
        return $response;
    }

    /**
     * Operation getSharedStepWithHttpInfo
     *
     * Get a specific shared step.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  string $hash Hash. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSharedStep'] to see the possible values for this operation
     *
     * @throws \Qase\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Qase\Client\Model\SharedStepResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSharedStepWithHttpInfo($code, $hash, string $contentType = self::contentTypes['getSharedStep'][0])
    {
        $request = $this->getSharedStepRequest($code, $hash, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Qase\Client\Model\SharedStepResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Qase\Client\Model\SharedStepResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Qase\Client\Model\SharedStepResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Qase\Client\Model\SharedStepResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Qase\Client\Model\SharedStepResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getSharedStepAsync
     *
     * Get a specific shared step.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  string $hash Hash. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSharedStep'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSharedStepAsync($code, $hash, string $contentType = self::contentTypes['getSharedStep'][0])
    {
        return $this->getSharedStepAsyncWithHttpInfo($code, $hash, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSharedStepAsyncWithHttpInfo
     *
     * Get a specific shared step.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  string $hash Hash. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSharedStep'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSharedStepAsyncWithHttpInfo($code, $hash, string $contentType = self::contentTypes['getSharedStep'][0])
    {
        $returnType = '\Qase\Client\Model\SharedStepResponse';
        $request = $this->getSharedStepRequest($code, $hash, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSharedStep'
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  string $hash Hash. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSharedStep'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getSharedStepRequest($code, $hash, string $contentType = self::contentTypes['getSharedStep'][0])
    {

        // verify the required parameter 'code' is set
        if ($code === null || (is_array($code) && count($code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $code when calling getSharedStep'
            );
        }
        if (strlen($code) > 10) {
            throw new \InvalidArgumentException('invalid length for "$code" when calling SharedStepsApi.getSharedStep, must be smaller than or equal to 10.');
        }
        if (strlen($code) < 2) {
            throw new \InvalidArgumentException('invalid length for "$code" when calling SharedStepsApi.getSharedStep, must be bigger than or equal to 2.');
        }
        
        // verify the required parameter 'hash' is set
        if ($hash === null || (is_array($hash) && count($hash) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $hash when calling getSharedStep'
            );
        }


        $resourcePath = '/shared_step/{code}/{hash}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($code !== null) {
            $resourcePath = str_replace(
                '{' . 'code' . '}',
                ObjectSerializer::toPathValue($code),
                $resourcePath
            );
        }
        // path params
        if ($hash !== null) {
            $resourcePath = str_replace(
                '{' . 'hash' . '}',
                ObjectSerializer::toPathValue($hash),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getSharedSteps
     *
     * Get all shared steps.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  string $search Provide a string that will be used to search by name. (optional)
     * @param  int $limit A number of entities in result set. (optional, default to 10)
     * @param  int $offset How many entities should be skipped. (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSharedSteps'] to see the possible values for this operation
     *
     * @throws \Qase\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Qase\Client\Model\SharedStepListResponse
     */
    public function getSharedSteps($code, $search = null, $limit = 10, $offset = 0, string $contentType = self::contentTypes['getSharedSteps'][0])
    {
        list($response) = $this->getSharedStepsWithHttpInfo($code, $search, $limit, $offset, $contentType);
        return $response;
    }

    /**
     * Operation getSharedStepsWithHttpInfo
     *
     * Get all shared steps.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  string $search Provide a string that will be used to search by name. (optional)
     * @param  int $limit A number of entities in result set. (optional, default to 10)
     * @param  int $offset How many entities should be skipped. (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSharedSteps'] to see the possible values for this operation
     *
     * @throws \Qase\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Qase\Client\Model\SharedStepListResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSharedStepsWithHttpInfo($code, $search = null, $limit = 10, $offset = 0, string $contentType = self::contentTypes['getSharedSteps'][0])
    {
        $request = $this->getSharedStepsRequest($code, $search, $limit, $offset, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Qase\Client\Model\SharedStepListResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Qase\Client\Model\SharedStepListResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Qase\Client\Model\SharedStepListResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Qase\Client\Model\SharedStepListResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Qase\Client\Model\SharedStepListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getSharedStepsAsync
     *
     * Get all shared steps.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  string $search Provide a string that will be used to search by name. (optional)
     * @param  int $limit A number of entities in result set. (optional, default to 10)
     * @param  int $offset How many entities should be skipped. (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSharedSteps'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSharedStepsAsync($code, $search = null, $limit = 10, $offset = 0, string $contentType = self::contentTypes['getSharedSteps'][0])
    {
        return $this->getSharedStepsAsyncWithHttpInfo($code, $search, $limit, $offset, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSharedStepsAsyncWithHttpInfo
     *
     * Get all shared steps.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  string $search Provide a string that will be used to search by name. (optional)
     * @param  int $limit A number of entities in result set. (optional, default to 10)
     * @param  int $offset How many entities should be skipped. (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSharedSteps'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSharedStepsAsyncWithHttpInfo($code, $search = null, $limit = 10, $offset = 0, string $contentType = self::contentTypes['getSharedSteps'][0])
    {
        $returnType = '\Qase\Client\Model\SharedStepListResponse';
        $request = $this->getSharedStepsRequest($code, $search, $limit, $offset, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSharedSteps'
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  string $search Provide a string that will be used to search by name. (optional)
     * @param  int $limit A number of entities in result set. (optional, default to 10)
     * @param  int $offset How many entities should be skipped. (optional, default to 0)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSharedSteps'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getSharedStepsRequest($code, $search = null, $limit = 10, $offset = 0, string $contentType = self::contentTypes['getSharedSteps'][0])
    {

        // verify the required parameter 'code' is set
        if ($code === null || (is_array($code) && count($code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $code when calling getSharedSteps'
            );
        }
        if (strlen($code) > 10) {
            throw new \InvalidArgumentException('invalid length for "$code" when calling SharedStepsApi.getSharedSteps, must be smaller than or equal to 10.');
        }
        if (strlen($code) < 2) {
            throw new \InvalidArgumentException('invalid length for "$code" when calling SharedStepsApi.getSharedSteps, must be bigger than or equal to 2.');
        }
        

        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling SharedStepsApi.getSharedSteps, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling SharedStepsApi.getSharedSteps, must be bigger than or equal to 1.');
        }
        
        if ($offset !== null && $offset > 100000) {
            throw new \InvalidArgumentException('invalid value for "$offset" when calling SharedStepsApi.getSharedSteps, must be smaller than or equal to 100000.');
        }
        if ($offset !== null && $offset < 0) {
            throw new \InvalidArgumentException('invalid value for "$offset" when calling SharedStepsApi.getSharedSteps, must be bigger than or equal to 0.');
        }
        

        $resourcePath = '/shared_step/{code}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $search,
            'search', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $offset,
            'offset', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($code !== null) {
            $resourcePath = str_replace(
                '{' . 'code' . '}',
                ObjectSerializer::toPathValue($code),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateSharedStep
     *
     * Update shared step.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  string $hash Hash. (required)
     * @param  \Qase\Client\Model\SharedStepUpdate $sharedStepUpdate sharedStepUpdate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateSharedStep'] to see the possible values for this operation
     *
     * @throws \Qase\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Qase\Client\Model\HashResponse
     */
    public function updateSharedStep($code, $hash, $sharedStepUpdate, string $contentType = self::contentTypes['updateSharedStep'][0])
    {
        list($response) = $this->updateSharedStepWithHttpInfo($code, $hash, $sharedStepUpdate, $contentType);
        return $response;
    }

    /**
     * Operation updateSharedStepWithHttpInfo
     *
     * Update shared step.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  string $hash Hash. (required)
     * @param  \Qase\Client\Model\SharedStepUpdate $sharedStepUpdate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateSharedStep'] to see the possible values for this operation
     *
     * @throws \Qase\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Qase\Client\Model\HashResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateSharedStepWithHttpInfo($code, $hash, $sharedStepUpdate, string $contentType = self::contentTypes['updateSharedStep'][0])
    {
        $request = $this->updateSharedStepRequest($code, $hash, $sharedStepUpdate, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Qase\Client\Model\HashResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Qase\Client\Model\HashResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Qase\Client\Model\HashResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Qase\Client\Model\HashResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Qase\Client\Model\HashResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateSharedStepAsync
     *
     * Update shared step.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  string $hash Hash. (required)
     * @param  \Qase\Client\Model\SharedStepUpdate $sharedStepUpdate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateSharedStep'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateSharedStepAsync($code, $hash, $sharedStepUpdate, string $contentType = self::contentTypes['updateSharedStep'][0])
    {
        return $this->updateSharedStepAsyncWithHttpInfo($code, $hash, $sharedStepUpdate, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateSharedStepAsyncWithHttpInfo
     *
     * Update shared step.
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  string $hash Hash. (required)
     * @param  \Qase\Client\Model\SharedStepUpdate $sharedStepUpdate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateSharedStep'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateSharedStepAsyncWithHttpInfo($code, $hash, $sharedStepUpdate, string $contentType = self::contentTypes['updateSharedStep'][0])
    {
        $returnType = '\Qase\Client\Model\HashResponse';
        $request = $this->updateSharedStepRequest($code, $hash, $sharedStepUpdate, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateSharedStep'
     *
     * @param  string $code Code of project, where to search entities. (required)
     * @param  string $hash Hash. (required)
     * @param  \Qase\Client\Model\SharedStepUpdate $sharedStepUpdate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateSharedStep'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateSharedStepRequest($code, $hash, $sharedStepUpdate, string $contentType = self::contentTypes['updateSharedStep'][0])
    {

        // verify the required parameter 'code' is set
        if ($code === null || (is_array($code) && count($code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $code when calling updateSharedStep'
            );
        }
        if (strlen($code) > 10) {
            throw new \InvalidArgumentException('invalid length for "$code" when calling SharedStepsApi.updateSharedStep, must be smaller than or equal to 10.');
        }
        if (strlen($code) < 2) {
            throw new \InvalidArgumentException('invalid length for "$code" when calling SharedStepsApi.updateSharedStep, must be bigger than or equal to 2.');
        }
        
        // verify the required parameter 'hash' is set
        if ($hash === null || (is_array($hash) && count($hash) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $hash when calling updateSharedStep'
            );
        }

        // verify the required parameter 'sharedStepUpdate' is set
        if ($sharedStepUpdate === null || (is_array($sharedStepUpdate) && count($sharedStepUpdate) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sharedStepUpdate when calling updateSharedStep'
            );
        }


        $resourcePath = '/shared_step/{code}/{hash}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($code !== null) {
            $resourcePath = str_replace(
                '{' . 'code' . '}',
                ObjectSerializer::toPathValue($code),
                $resourcePath
            );
        }
        // path params
        if ($hash !== null) {
            $resourcePath = str_replace(
                '{' . 'hash' . '}',
                ObjectSerializer::toPathValue($hash),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($sharedStepUpdate)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($sharedStepUpdate));
            } else {
                $httpBody = $sharedStepUpdate;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
