<?php
/**
 * MilestonesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Qase\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Qase.io API
 *
 * Qase API Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Qase\Client\Test\Api;

use \Qase\Client\Configuration;
use \Qase\Client\ApiException;
use \Qase\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MilestonesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Qase\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MilestonesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createMilestone
     *
     * Create a new milestone..
     *
     */
    public function testCreateMilestone()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteMilestone
     *
     * Delete milestone..
     *
     */
    public function testDeleteMilestone()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMilestone
     *
     * Get a specific milestone..
     *
     */
    public function testGetMilestone()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMilestones
     *
     * Get all milestones..
     *
     */
    public function testGetMilestones()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateMilestone
     *
     * Update milestone..
     *
     */
    public function testUpdateMilestone()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
