<?php
/**
 * ResultsApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  Qase\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Qase.io API
 *
 * Qase API Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Qase\Client\Test\Api;

use \Qase\Client\Configuration;
use \Qase\Client\ApiException;
use \Qase\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ResultsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Qase\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ResultsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createResult
     *
     * Create test run result..
     *
     */
    public function testCreateResult()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createResultBulk
     *
     * Bulk create test run result..
     *
     */
    public function testCreateResultBulk()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteResult
     *
     * Delete test run result..
     *
     */
    public function testDeleteResult()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getResult
     *
     * Get test run result by code..
     *
     */
    public function testGetResult()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getResults
     *
     * Get all test run results..
     *
     */
    public function testGetResults()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateResult
     *
     * Update test run result..
     *
     */
    public function testUpdateResult()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
